### ISSUE TITLE
ULID Support 

### ISSUE THREAD

**Issue by techdragon** [codingjoe/django-dynamic-filenames#9]
Support for https://github.com/ulid/spec would require either a lot more code, or the inclusion of a new (optional?) dependency. 

If you're ok with adding the feature & dependency, I'm happy to write a PR for this.

**Comment by codingjoe** [comment]
Hi @techdragon,

Thank you for reaching out. Interesting, I've never heard of ULID… and I don't seem to be alone with that. There are currently multiple more or less well-maintained libraries on PyPi, and I don't feel too comfortably using any of them.

Besides, I don't really understand the upside or ULID right now. Maybe you could explain me your use case a little. What make it preferable in your use case to UUID.

Oh, and please pardon the late response, this must have slipped past me somehow.
Since this request is so old, I'll close it for now and reopen it, should there be any sustained interest.

Best,
Joe
